# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/shopping_cart
spring.datasource.username=postgres
spring.datasource.password=1031
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# HIBERNATE & JPA SETTINGS
# ===============================
# 'update' tells Spring to automatically create the tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update
# Shows the SQL queries in the terminal so you can see what Spring is doing
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT SECURITY SETTINGS
# ===============================
# A secure, 256-bit Base64 encoded secret key
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiration time in milliseconds (86400000 ms = 24 hours)
application.security.jwt.expiration=86400000